name: Transform Design Tokens with Style Dictionary

on:
  push:
    branches:
      - main
    paths:
      - "tokens/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate package-lock.json
        run: npm install --package-lock-only

      - name: Commit package-lock.json if missing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package-lock.json || echo "No package-lock.json to add"
          git commit -m "chore: add package-lock.json" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Validate JSON Files
        run: |
          for file in tokens/*.json; do
            echo "Validating $file..."
            cat $file | jq empty || (echo "❌ Invalid JSON in $file"; exit 1)
          done
      - name: Flatten and clean the JSON
        run: node flatten.js

      - name: Run Style Dictionary transformation
        run: |
          npx style-dictionary build --config style-dictionary.config.js

      - name: Commit and push transformed tokens
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "chore: update transformed design tokens" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main || echo "No changes to push"



